<?php

namespace lexiktestBundle\Repository;

/**
 * GroupsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupsRepository extends \Doctrine\ORM\EntityRepository
{
    public function getGroupByName($group) {
        $query = $this->createQueryBuilder('groups')
            ->where('groups.name = :group')
            ->setParameter('group', $group);
        $res = $query->getQuery()->getResult();
        return $res;
    }
}
